name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install required Rust targets
        run: rustup target add x86_64-unknown-linux-gnu

      - name: run tests
        run: |
          echo 'running test without asm-keccak'
          CARGO_INCREMENTAL=false cargo test -- tests::test_foo_fails --exact --show-output
          echo '..'
          echo 'running test with asm-keccak'
          CARGO_INCREMENTAL=false cargo test --features asm-keccak -- tests::test_foo_fails --exact --show-output
